# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Post.destroy_all
City.destroy_all

atlanta = City.new
atlanta.name = "Atlanta"
atlanta.image = "https://lh3.googleusercontent.com/hLkjLFzbyjJwXKLB5GwL0zPEfb0uVY3V8KgEwGY3kPRkZ6qSEVDnLraeT8A8NmnOwsb6ZDE=s170"
atlanta.save


post1 = atlanta.posts.create(title: "Sweet Water Creek State Park", description: "Sweetwater Creek State Park is a peaceful tract of wilderness only minutes from downtown Atlanta. A wooded trail follows the stream to the ruins of the New Manchester Manufacturing Company, a textile mill burned during the Civil War. Beyond the mill, the trail climbs rocky bluffs to provide views of the beautiful rapids below. Additional trails wind through fields and forest, showcasing ferns, magnolias, wild azaleas and hardwoods. Park rangers lead informative hikes to these areas throughout the year. The 215 acre George Sparks Reservoir is popular for fishing and provides a pretty setting for feeding ducks and picnicking. However, there is no beach and swimming in the Reservoir is not allowed. Fishing supplies are available in the adjacent bait shop. During warmer months, the park rents fishing boats, canoes, kayaks, stand-up paddleboards and pedal boats. Visitors can join the Park Paddlers Club, which challenges them to explore waterways in six state parks. An award-winning Visitor Center—one of the most environmentally responsible buildings in the country—features exhibits on the area’s history, wildlife displays, trail maps, snacks and a renovated gift shop. A window-lined meeting room that seats 40 can be rented for gatherings.")
post2 = atlanta.posts.create(title: "Oakland Cemetary", description: "Less than a mile from the heart of downtown Atlanta, a hidden treasure, a secret sanctuary, welcomes you. This garden cemetery, founded in 1850, is the final resting place of many of Atlanta’s settlers, builders, and most noted citizens like Bobby Jones, Margaret Mitchell, and Maynard Jackson. It is also a showplace of sculpture and architecture, and a botanical preserve with ancient oaks and magnolias. Here in this peaceful place the full scope of the city’s rich and fascinating history unfolds before you.")
post3 = atlanta.posts.create(title: "Little Five Points", description: "Little Five Points is renowned for its alternative culture.[4] It is home to metro-wide indie radio station WRFG FM 89.3, two independent bookstores (Charis Books and More and A Cappella Books), a skateshop staffed by some pro skateboarders (Stratosphere Skateboards), record stores (Criminal Records,[5] Wax'n'Facts, and Moods Music), coffee shops (Java Lords, Aurora Coffee, Starbucks), a health and wellness center (Sweetgrass Wellness Spring), new and used clothing stores (Rag-O-Rama), a shoe store (Abbadabba's) novelty shops (Junkman's Daughter), a new-age shop (Crystal Blue), a locally owned credit union (BOND Community Federal Credit Union),[6] a natural foods store (Sevananda Natural Foods Market),[7] an independent pharmacy, and independent record labels (DB Records) and Shut Eye Records & Agency, two theaters (7Stages and Horizon Theatre), a major music venue (Variety Playhouse), a community music school (The Little 5 Points Music Center),[8] a smoking store (42°), and several local restaurants and bars. The neighborhood is featured in the Cartoon Network show Class of 3000 as well as the Internet Girls series of books by Lauren Myracle, who mentions several of the businesses in Little Five Points by name. Little Five points is home to the Little Five Points Halloween Festival, which takes place every year on the Saturday of Halloween. The official L5P Poet used to freestyle poetry in the square and has a mural located in the alley way between Earthtones and American Apparel; he has not been present in 2014. Local vendors sell arts and crafts and the highlight of the celebration is the Little Five Points Halloween Parade. The parade features local celebrities, bikers in costume, live music, hearses, several local marching bands, and many parade floats that are put together by community action groups and local businesses.[9] Little Five is also the host of Little Five Fest, which is an annual music festival featuring 50-100 local bands spread across multiple venues. [1] Mural by Jerkface of Jerry the mouse in Little Five Points Atlanta Mural by Jerkface in Little Five Points Little Five Points is one of Atlanta's best neighborhoods for viewing street art. Unlike most of Atlanta's neighborhoods, the street art in Little Five Points is highly concentrated in a compact easily walked area. Works by internationally known street artists such as Jerkface can be found as well as works by local artist such as Chris Veal and R. Land. But finding the murals can be a bit of a treasure hunt. Many works of street art are tucked away on the back sides of buildings, in alleyways, and in back parking lots. Both the easily visible and hidden gems of street art in Little Five Points are mapped on the Atlanta Street Art Map.[10]")
post4 = atlanta.posts.create(title: "Martin Luther King Jr. Museum", description: "A young boy grows up in a time of segregation…A dreamer is moved by destiny into leadership of the modern civil rights movement…This was Martin Luther King, Jr.  Come hear his story, visit the home of his birth, and where he played as a child.  Walk in his footsteps, and hear his voice in the church where he moved hearts and minds.  Marvel at how he was an instrument for social change.")
post5 = atlanta.posts.create(title: "BeltLine", description: "The Atlanta BeltLine is a planned loop of 22 miles of modern streetcar (an expansion of the Atlanta Streetcar), 33 miles of multi-use trail, and 2,000 acres of parks. It will open in phases through the anticipated completion in 2030. As of 2016, the Atlanta BeltLine consists of four open trails; two trails under construction; seven parks; intensive planning for modern streetcar expansion; more than $3 billion in private economic redevelopment; hundreds of affordable workforce homes; free fitness classes; a linear arboretum; and urban farm; and the largest temporary public art exhibition in the south. First conceived as a 1999 master’s thesis by Georgia Tech student Ryan Gravel, the Atlanta BeltLine evolved from an idea, to a grassroots campaign of local citizens and civic leaders, into a robust new vision of an Atlanta dedicated to an integrated approach to transportation, land use, greenspace, and sustainable growth.")

london = City.create(name: "London", image: "https://images.unsplash.com/photo-1508711046474-2f4c2d3d30ca?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=d9753d35c4f5b62442eb81568033ddc2&auto=format&fit=crop&w=2850&q=80")

post6 = london.posts.create(title: "Tower of London", description: "One of London's most famous landmarks, the historic Tower houses the Crown Jewels, the prison cell of Sir Walter Raleigh, known as the Bloody Tower, and the Chapel of St. John and the Royal Armories.")
post7 = london.posts.create(title: "Houses of Parliament", description: "Most of this iconic building was built in the mid-19th century following a devastating fire in 1834. Westminster Hall survived the fire and dates from 1097. Visitors can book tours through the House of Commons and the House of Lords, and are welcome to watch debates and committees when the Houses are sitting.")
post8 = london.posts.create(title: "Tower Bridge", description: "An iconic London landmark and one of Britain's best loved historic sites, Tower Bridge is open to the public 363 days a year. Within the Bridge's iconic structure and magnificent Victorian Engine rooms, the Tower Bridge Exhibition is the best way of exploring the most famous bridge in the world! Come learn about this incredible feat of Victorian engineering, discover how the Bridge is raised and enjoy stunning panoramic views across London from our high-level walkways, 42 metres above the River Thames. Opening Times: 10:00 - 17:30(last admission )")
post9 = london.posts.create(title: "St. Jame's Park", description: "This 90-acre park, the oldest Royal Park in London, features a large lake that is a wildlife sanctuary for ducks, geese, swans and even pelicans.")
post10 = london.posts.create(title: "Hyde Park", description: "Once the hunting ground for Henry VIII, this large royal park is best known for its famous Speakers' Corner, where people speak their minds, Rotton Row, a famous horse-riding area and Serpentine Lake, home to waterfowl and oarsmen.")

sf = City.create(name: "San Francisco", image: "https://images.unsplash.com/photo-1449034446853-66c86144b0ad?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=7402cc297bdfbb4a4856e764971dc013&auto=format&fit=crop&w=1950&q=80")

post11 = sf.posts.create(title: "Golden Gate Bridge", description: "The Golden Gate Bridge is a suspension bridge spanning the Golden Gate, the one-mile-wide strait connecting San Francisco Bay and the Pacific Ocean.")
post11 = sf.posts.create(title: "Fisherman's Wharf", description: "Fisherman’s Wharf, on the northern waterfront, is one of the city's busiest tourist areas. Souvenir shops and stalls selling crab and clam chowder in sourdough bread bowls appear at every turn, as do postcard views of the bay, Golden Gate and Alcatraz. There’s also a colony of sea lions to see and historic ships to tour. At Ghirardelli Square, boutiques and eateries reside in the famed former chocolate factory.")
post11 = sf.posts.create(title: "Alcatraz Island", description: "Alcatraz Island is located in San Francisco Bay, 1.25 miles offshore from San Francisco, California, United States.")
post11 = sf.posts.create(title: "Union Square", description: "Union Square is the teeming commercial hub of the city. Many major hotels and department stores are packed into the area surrounding the actual square. Numerous upscale boutiques, restaurants, nightspots and galleries occupy the spaces tucked between the larger buildings. At the intersection of Powell and Market streets, tourists huddle to view one the city’s most unique sites, the manual cable car turnaround.")
post11 = sf.posts.create(title: "Pier 39", description: "Pier 39 is a shopping center and popular tourist attraction built on a pier in San Francisco, California")